---
- name: Configure minotauro box
  hosts: all
  sudo: true
  vars_files:
    - vars/main.yml
  roles:
    ### Server provisioning roles:
    - { role: linux-prereqs, tags: ['linux-prereqs'] }
    # - { role: mysql, tags: ['mysql'] }
    - { role: postgresql, tags: ['postgresql'] }
    # - { role: mongodb, tags: ['mongodb'] }
    - { role: znzj.rbenv, rbenv_ruby_version: "2.2.2" }
    - { role: redis, tags: ['redis'] }
    # - { role: elasticsearch, tags: ['elasticsearch'] }
